INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	25);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	26);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	27);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	28);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	29);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	30);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	31);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	32);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	33);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	34);
INSERT INTO  major (dname, sid) VALUES ('Chemical Engineering',	35);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	36);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	37);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	38);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	39);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	40);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	41);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	42);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	43);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	44);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	45);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	46);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	47);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	48);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	49);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	50);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	51);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	52);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	53);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	54);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	55);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	56);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	57);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	58);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	59);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	60);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	61);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	62);
INSERT INTO  major (dname, sid) VALUES ('Civil Engineering',	63);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	1);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	2);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	3);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	4);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	5);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	6);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	7);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	8);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	9);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	10);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	11);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	12);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	13);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	14);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	15);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	16);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	17);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	18);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	19);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	20);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	21);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	22);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	23);
INSERT INTO  major (dname, sid) VALUES ('Computer Sciences',	24);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	64);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	65);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	66);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	67);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	68);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	69);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	70);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	71);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	72);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	73);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	74);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	75);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	76);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	77);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	78);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	79);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	80);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	81);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	82);
INSERT INTO  major (dname, sid) VALUES ('Industrial Engineering',	83);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	10);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	1);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	2);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	3);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	84);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	85);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	86);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	87);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	88);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	89);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	90);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	91);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	92);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	93);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	94);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	95);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	96);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	97);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	98);
INSERT INTO  major (dname, sid) VALUES ('Mathematics',	99);
INSERT INTO  major (dname, sid) VALUES ('Sanitary Engineering',	4);