INSERT INTO  prof (pname, dname) VALUES ('Brian, C.',	'Computer Sciences');
INSERT INTO  prof (pname, dname) VALUES ('Brown, S.',	'Civil Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Bucket, T.',	'Sanitary Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Clark, E.',	'Civil Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Edison, L.',	'Chemical Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Jones, J.',	'Computer Sciences');
INSERT INTO  prof (pname, dname) VALUES ('Randolph, B.',	'Civil Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Robinson, T.',	'Mathematics');
INSERT INTO  prof (pname, dname) VALUES ('Smith, S.',	'Industrial Engineering');
INSERT INTO  prof (pname, dname) VALUES ('Walter, A.',	'Industrial Engineering');
