INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Chemical Engineering',	310,	1,	'Edison, L.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Civil Engineering',	365,	1,	'Randolph, B.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Civil Engineering',	375,	1,	'Brown, S.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Civil Engineering',	561,	1,	'Randolph, B.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Computer Sciences',	302,	1,	'Jones, J.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Computer Sciences',	302,	2,	'Smith, S.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Computer Sciences',	467,	1,	'Jones, J.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Computer Sciences',	701,	1,	'Clark, E.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Computer Sciences',	726,	1,	'Brian, C.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Industrial Engineering',	514,	1,	'Walter, A.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Mathematics',	461,	1,	'Robinson, T.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Mathematics',	462,	1,	'Robinson, T.');
INSERT INTO  section (dname, cno, sectno, pname) VALUES ('Sanitary Engineering',	561,	1,	'Bucket, T.');
