INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (1,	3.00,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (2,	3.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (3,	3.50,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (4,	4.00,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (5,	3.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (6,	3.50,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (7,	4.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (8,	4.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (9,	3.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (10,	2.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (11,	3.00,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (12,	2.50,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (13,	2.50,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (14,	2.50,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (15,	3.00,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (16,	3.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (16,	3.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (17,	3.00,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (18,	2.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (18,	3.50,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (19,	3.50,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (20,	2.50,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (21,	3.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (21,	3.50,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (22,	3.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (22,	3.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (23,	4.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (24,	4.00,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (25,	3.50,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (26,	3.50,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (27,	2.50,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (28,	3.00,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (29,	3.00,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (29,	3.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (29,	3.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (30,	4.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (31,	3.50,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (32,	2.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (33,	2.00,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (33,	3.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (34,	1.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (35,	3.00,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (36,	3.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (37,	3.00,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (38,	3.00,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (39,	3.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (40,	3.50,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (41,	3.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (42,	3.50,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (43,	2.50,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (44,	4.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (45,	3.00,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (46,	4.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (47,	1.00,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (47,	0.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (48,	1.50,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (49,	3.50,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (49,	3.50,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (50,	4.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (51,	3.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (52,	1.00,	'Computer Sciences',	302,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (52,	4.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (53,	4.00,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (54,	3.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (55,	2.50,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (56,	2.50,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (57,	3.50,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (58,	2.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (59,	3.50,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (60,	2.50,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (61,	3.50,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (61,	2.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (62,	2.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (63,	2.50,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (64,	4.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (64,	3.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (66,	1.50,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (66,	4.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (67,	3.50,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (67,	4.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (68,	3.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (69,	3.50,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (69,	2.00,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (70,	3.50,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (71,	2.50,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (72,	3.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (73,	3.00,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (74,	2.50,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (75,	3.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (76,	3.50,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (77,	2.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (78,	3.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (79,	4.00,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (80,	4.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (81,	2.50,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (82,	3.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (83,	3.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (84,	3.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (85,	3.50,	'Civil Engineering',	375,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (86,	2.50,	'Computer Sciences',	467,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (86,	3.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (87,	4.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (88,	2.00,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (89,	3.50,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (90,	3.50,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (90,	3.50,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (91,	4.00,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (92,	4.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (93,	4.00,	'Chemical Engineering',	310,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (94,	2.00,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (96,	4.00,	'Civil Engineering',	365,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (96,	3.00,	'Civil Engineering',	561,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (97,	3.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (98,	4.00,	'Industrial Engineering',	514,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (99,	3.50,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (100,	2.00,	'Computer Sciences',	726,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (101,	4.00,	'Mathematics',	462,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (102,	3.50,	'Mathematics',	461,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (103,	4.00,	'Computer Sciences',	701,	1);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (104,	2.80,	'Computer Sciences',	302,	2);
INSERT INTO  enroll (sid, grade, dname, cno, sectno) VALUES (104,	2.60,	'Sanitary Engineering',	561,	1);
