INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (1,	'Jacobs, T.',	'm',	29,	5,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (2,	'Pierson, E.',	'm',	32,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (3,	'Zeene, Ben N.',	'm',	21,	5,	3.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (4,	'Sulfate, Barry M.',	'm',	19,	2,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (5,	'Form, Clara O.',	'f',	18,	1,	3.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (6,	'Scott, Kim J.',	'm',	20,	1,	3.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (7,	'Sather, Roberto B.',	'm',	22,	4,	2.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (8,	'Stanley, Leotha T.',	'm',	21,	3,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (9,	'Smith, Joyce A.',	'f',	21,	4,	2.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (10,	'Jones, David S.',	'm',	19,	2,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (11,	'Paul, Mary W.',	'f',	23,	5,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (12,	'Soong, V.',	'f',	24,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (13,	'Kellerman, S.',	'f',	21,	3,	2.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (14,	'Cheong, R.',	'm',	25,	4,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (15,	'Borchart, Sandra L.',	'f',	26,	5,	3.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (16,	'Alsberg, David J.',	'm',	25,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (17,	'Thorton, James Q.',	'm',	28,	4,	2.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (18,	'Gooch',	'm',	26,	1,	1.40);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (19,	'Smith, L.',	'm',	43,	4,	0.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (20,	'Korpel, E.',	'f',	19,	3,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (21,	'Surk, K.',	'm',	23,	2,	2.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (22,	'Emile, R.',	'm',	18,	1,	2.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (23,	'Bomber, C.',	'f',	22,	4,	3.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (24,	'Carter, Jimmy',	'm',	56, 5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (25,	'Kissinger, Henry',	'm',	58,	5,	3.40);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (26,	'Ford, Gerald',	'm',	60,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (27,	'Anderson, P.',	'f',	18,	1,	3.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (28,	'Austin, G.',	'm',	25,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (29,	'Hamilton, S.',	'm',	21,	3,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (30,	'Baker, C.',	'f',	18,	1,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (31,	'Andrews, R.',	'm',	19,	2,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (32,	'Liu, Huihusan',	'm',	29,	5,	3.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (33,	'Chao, Tsechih',	'f',	23,	5,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (34,	'Kasten, Norman L.',	'm',	23,	2,	2.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (35,	'Mathews, John W.',	'm',	29,	5,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (36,	'Burroughs, Susan S.',	'f',	18,	1,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (37,	'Dunbar, D.',	'm',	30,	5,	3.40);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (38,	'Auen, B.',	'm',	21,	3,	2.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (39,	'Shoemaker, A.',	'f',	22,	4,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (40,	'Rosemeyer, S.',	'f',	21,	3,	2.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (41,	'Fisher, C.',	'f',	22,	4,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (42,	'Trude, T.',	'm',	19,	2,	2.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (43,	'Ksar, J.',	'm',	20,	3,	3.40);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (44,	'Moeri, S.',	'f',	20,	4,	3.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (45,	'June, Granson',	'f',	18,	1,	3.10);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (46,	'Micheal, Zadicki T.',	'm',	22,	2,	2.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (47,	'Roger, Blotter N.',	'm',	21,	3,	1.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (48,	'Natividad, A.',	'f',	25,	5,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (49,	'Villa-lobos, M.',	'm',	47,	5,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (50,	'Moomchi, B.',	'm',	32,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (51,	'Jetplane, Leaving O.',	'm',	30,	1,	0.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (52,	'Fy, Clara I.',	'f',	18,	2,	2.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (53,	'Atny, Mary H.',	'f',	26,	5,	3.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (54,	'Maximillian',	'm',	98,	5,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (55,	'Glitch, R.',	'm',	19,	1,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (56,	'Starry, J.',	'f',	22,	4,	3.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (57,	'Hiemerschmitz, A.',	'f',	19,	1,	2.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (58,	'Marshmallton',	'm',	20,	3,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (59,	'Ziebart, F.',	'm',	22,	4,	1.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (60,	'Calcmity, J.',	'f',	23,	3,	2.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (61,	'Kennedy, Ed',	'm',	55,	3,	2.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (62,	'Moses, A.',	'm',	18,	1,	3.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (63,	'Kool, Joseph F.',	'm',	35,	5,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (64,	'Fred, Edwin B.',	'm',	80,	5,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (65,	'Ripper, Jack T.',	'm',	18,	1,	0.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (66,	'Altenhaus, Stuart',	'm',	21,	4,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (67,	'Altenhaus, Gloria',	'f',	22,	5,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (68,	'Crist, J.',	'm',	23,	4,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (69,	'Heilskov, G.',	'm',	23,	4,	2.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (70,	'Caucutt, B.',	'm',	24,	5,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (71,	'Mark, B.',	'm',	24,	4,	3.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (72,	'Barnes, J.',	'm',	45,	5,	2.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (73,	'Quarnty, G.',	'f',	20,	2,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (74,	'Andrus, J.',	'f',	21,	3,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (75,	'Jones, A.',	'f',	23,	5,	3.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (76,	'Zorhoff, C.',	'm',	20,	3,	3.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (77,	'Paull, Thomas H.',	'm',	23,	4,	2.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (78,	'Cool, J.',	'm',	18,	2,	2.60);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (79,	'Evert, Chris',	'f',	21,	4,	3.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (80,	'Connors, Jimmy',	'm',	25,	1,	0.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (81,	'Smith, Ike Z.',	'm',	33,	1,	1.10);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (82,	'News, Nightly',	'm',	15,	1,	1.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (83,	'Jones, Ivan L.',	'm',	55,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (84,	'Smith, R.',	'm',	19,	3,	2.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (85,	'Mayer, N.',	'f',	21,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (86,	'Gonring, J.',	'm',	21,	4,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (87,	'Mueller, D.',	'm',	20,	3,	3.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (88,	'Bates, M.',	'm',	22,	4,	3.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (89,	'Longlastname, A.',	'f',	99,	5,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (90,	'Zappa, F.',	'm',	16,	4,	4.00);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (91,	'Ghandi, I.',	'f',	78,	1,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (92,	'Kirk, J.',	'm',	34,	5,	2.20);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (93,	'Andermanthenol, K.',	'm',	26,	5,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (94,	'Uoiea, Z.',	'f',	19,	2,	3.30);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (95,	'Grzlbltz, Q.',	'm',	43,	5,	2.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (96,	'Birch, M.',	'f',	23,	5,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (97,	'Morgan, D.',	'm',	18,	1,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (98,	'Taylor, R.',	'm',	20,	3,	2.80);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (99,	'Jones, J.',	'f',	21,	1,	1.10);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (100,	'Gringo, C.',	'm',	25,	5,	2.90);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (101,	'Davis, Scott P.',	'm',	19,	3,	3.70);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (102,	'Bates, Michael L.',	'm',	22,	4,	3.40);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (103,	'Kaisler, Janet M.',	'f',	21,	4,	3.50);
INSERT INTO  student (sid, sname, sex, age, year, gpa) VALUES (104,	'Baskett, Wayse T.',	'm',	23,	3,	2.10);